[package]
name = "maca-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "maca"
path = "src/main.rs"

[dependencies]
maca-parser = { path = "../parser" }
maca-core = { path = "../core" }
maca-backend-c = { path = "../backend_c" }
maca-backend-llvm = { path = "../backend_llvm" }
maca-backend-nix = { path = "../backend_nix" }
maca-backend-js = { path = "../backend_js" }
maca-backend-jvm = { path = "../backend_jvm" }
maca-backend-embedded = { path = "../backend_embedded" }
maca-runtime = { path = "../runtime" }
maca-profile = { path = "../profile" }
serde_json = "1"
