[package]
name = "maca-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
maca-lexer = { path = "../lexer" }
maca-parser = { path = "../parser" }
maca-core = { path = "../core" }
maca-lsp = { path = "../lsp" }
maca-backend-c = { path = "../backend_c" }
maca-backend-js = { path = "../backend_js" }
maca-backend-nix = { path = "../backend_nix" }
maca-profile = { path = "../profile" }
