//! `maca bindgen <header.h>` — generate Maca FFI declarations from a C header.
//!
//! A lightweight prototype scanner (no libclang): it strips comments and
//! preprocessor lines, splits the remaining text into `;`-terminated
//! declarations, and turns each function prototype `RET NAME(PARAMS)` into a
//! Maca extern declaration `name(arg: T, …) -> R`. C types map to Maca's:
//! `char*`/`const char*` → `str`, other pointers → `int` (an opaque handle),
//! `double`/`float` → `float`, and the integer family → `int`. Good enough for
//! the common C API surface; hand-edit the result for anything exotic.

use std::path::{Path, PathBuf};

pub fn cmd_bindgen(args: &[String]) {
    let mut header: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "-o" => out = it.next().map(PathBuf::from),
            _ => header = Some(PathBuf::from(a)),
        }
    }
    let Some(header) = header else {
        eprintln!("bindgen: expected a C header (usage: maca bindgen <header.h> [-o out.maca])");
        std::process::exit(2);
    };
    let src = match std::fs::read_to_string(&header) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("bindgen: cannot read {}: {e}", header.display());
            std::process::exit(1);
        }
    };
    let maca = generate(&src, &header);
    match out {
        Some(p) => match std::fs::write(&p, &maca) {
            Ok(()) => println!("wrote {}", p.display()),
            Err(e) => {
                eprintln!("bindgen: cannot write {}: {e}", p.display());
                std::process::exit(1);
            }
        },
        None => print!("{maca}"),
    }
}

/// The Maca module text for a header's function prototypes.
pub fn generate(src: &str, header: &Path) -> String {
    let cleaned = strip(src);
    let name = header
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "header.h".into());
    let mut out = format!(
        "// Generated by `maca bindgen {name}` — Maca FFI declarations.\n\
         // Pointers become opaque `int` handles; `char*` becomes `str`.\nimport c \"{name}\"\n\n"
    );
    let mut count = 0;
    for decl in cleaned.split(';') {
        if let Some(line) = prototype(decl) {
            out.push_str(&line);
            out.push('\n');
            count += 1;
        }
    }
    if count == 0 {
        out.push_str("// (no function prototypes found)\n");
    }
    out
}

/// Remove `//` and `/* */` comments and `#` preprocessor lines, collapsing the
/// rest to whitespace-separated tokens across lines.
fn strip(src: &str) -> String {
    // block comments
    let mut s = String::with_capacity(src.len());
    let b = src.as_bytes();
    let mut i = 0;
    while i < b.len() {
        if i + 1 < b.len() && b[i] == b'/' && b[i + 1] == b'*' {
            i += 2;
            while i + 1 < b.len() && !(b[i] == b'*' && b[i + 1] == b'/') {
                i += 1;
            }
            i += 2;
        } else {
            s.push(b[i] as char);
            i += 1;
        }
    }
    // line comments + preprocessor
    s.lines()
        .map(|l| {
            let l = l.split("//").next().unwrap_or("");
            if l.trim_start().starts_with('#') {
                ""
            } else {
                l
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// If `decl` is a function prototype, return its Maca declaration line.
fn prototype(decl: &str) -> Option<String> {
    let decl = decl.trim();
    if decl.is_empty() {
        return None;
    }
    let open = decl.find('(')?;
    let close = decl.rfind(')')?;
    if close < open {
        return None;
    }
    let head = &decl[..open];
    let params = &decl[open + 1..close];
    // skip typedefs, struct/enum/union decls, and anything with no name
    if head.contains("typedef")
        || head.contains("struct")
        || head.contains("enum")
        || head.contains("union")
    {
        return None;
    }
    // a function pointer (`(*name)`) or macro call isn't a plain prototype
    if params.contains("(*") || decl.contains("=") {
        return None;
    }
    // the name is the last identifier in the head; the return type is the rest.
    let name = last_ident(head)?;
    if name.is_empty() {
        return None;
    }
    let ret_c = head[..head.len() - name.len()].trim();
    let ret = map_type(ret_c);
    let ps = map_params(params);
    Some(format!("{name}({ps}) -> {ret}"))
}

/// The trailing C identifier of a string (`const char *sqlite3_libversion` →
/// `sqlite3_libversion`), skipping trailing `*`/spaces.
fn last_ident(s: &str) -> Option<String> {
    let t = s.trim_end_matches(['*', ' ', '\t', '\n']);
    let start = t
        .rfind(|c: char| !(c.is_alphanumeric() || c == '_'))
        .map(|i| i + 1)
        .unwrap_or(0);
    let id = &t[start..];
    if id.is_empty() || id.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        None
    } else {
        Some(id.to_string())
    }
}

fn map_params(params: &str) -> String {
    let p = params.trim();
    if p.is_empty() || p == "void" {
        return String::new();
    }
    p.split(',')
        .enumerate()
        .map(|(i, raw)| {
            let raw = raw.trim();
            let name = last_ident(raw).filter(|n| !is_c_type_word(n));
            let ty = match &name {
                // a named parameter: type is everything before the name
                Some(n) => map_type(raw[..raw.len().saturating_sub(n.len())].trim()),
                None => map_type(raw),
            };
            let n = name.unwrap_or_else(|| format!("a{i}"));
            format!("{n}: {ty}")
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// A bare type keyword that shouldn't be mistaken for a parameter name (an
/// unnamed `int` parameter's "last identifier" is `int`).
fn is_c_type_word(w: &str) -> bool {
    matches!(
        w,
        "void"
            | "int"
            | "char"
            | "short"
            | "long"
            | "float"
            | "double"
            | "unsigned"
            | "signed"
            | "size_t"
            | "int8_t"
            | "int16_t"
            | "int32_t"
            | "int64_t"
            | "uint8_t"
            | "uint16_t"
            | "uint32_t"
            | "uint64_t"
            | "bool"
    )
}

/// Map a C type to a Maca type: `char*` → `str`, other pointers → `int`
/// (opaque handle), floating types → `float`, everything else → `int`.
fn map_type(c: &str) -> &'static str {
    let t = c.trim();
    if t.contains('*') {
        if t.contains("char") && !t.contains("char**") {
            return "str";
        }
        return "int"; // opaque handle
    }
    if t.contains("double") || t.contains("float") {
        return "float";
    }
    "int"
}
